// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQJ0_npHJRsBztFS4cF59FJCJDeO0YWsk',
    appId: '1:689239661436:android:9180d9dbac2eaaa707a2f9',
    messagingSenderId: '689239661436',
    projectId: 'suponotechtask',
    storageBucket: '"suponotechtask.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi7holi1cluznZ54ufFNNk_aQVXf77vek',
    appId: '1:689239661436:ios:4fe5941094deb08a07a2f9',
    messagingSenderId: '689239661436',
    projectId: 'suponotechtask',
    storageBucket: 'suponotechtask.firebasestorage.app',
    iosBundleId: 'com.khumoyiddinbakhodirov.flutter',
  );
}
